services:

  con4gis\FrameworkBundle\Classes\Service\PageUrlService:
    public: true

  con4gis\FrameworkBundle\Controller\DemoTableModuleController:
    class: con4gis\FrameworkBundle\Controller\DemoTableModuleController
    public: true

  con4gis\FrameworkBundle\Controller\DemoTileListModuleController:
    class: con4gis\FrameworkBundle\Controller\DemoTileListModuleController
    public: true

  con4gis\FrameworkBundle\Controller\DemoDetailModuleController:
    class: con4gis\FrameworkBundle\Controller\DemoDetailModuleController
    public: true

  con4gis\FrameworkBundle\Controller\DemoFormModuleController:
    class: con4gis\FrameworkBundle\Controller\DemoFormModuleController
    public: true